apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nasa-nad1
  annotations:
    juniper.net/networks: '{
      "ipamV4Subnet": "172.15.20.0/24"
    }'
spec:
  config: '{
  "cniVersion": "0.3.1",
  "name": "nasa-nad1",
  "type": "contrail-k8s-cni"
}'
