apiVersion: v1
kind: Pod
metadata:
  name: mynad-sriov-pod-3
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net1, mynet-nw
spec:
  containers:
  - name:  mynad-sriov-pod-3
    image: centos/tools 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/intel_sriov_netdevice: '1'
      limits:
        intel.com/intel_sriov_netdevice: '1'
---
apiVersion: v1
kind: Pod
metadata:
  name: mynad-sriov-pod-4
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net1, mynet-nw
spec:
  containers:
  - name:  mynad-sriov-pod-4
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/intel_sriov_netdevice: '1'
      limits:
        intel.com/intel_sriov_netdevice: '1'
